version: "3.0"

services:

  main:
    container_name: main
    build:
       context: .
    env_file:
      - .release.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 7000:7000
      - 9229:9299
    command:
      npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .release.env
    environment:
      PG_DATA: /var/lib/postgres/data
    ports:
      - 5432:5432
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

